spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/ai_db
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    open-in-view: false
#  sql:
#    init:
#      mode: never
#  batch:
#    jdbc:
#      initialize-schema: never