spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/ai_db
  jpa:
    defer-datasource-initialization: true
#    hibernate.ddl-auto: create
    hibernate.ddl-auto: none
#    show-sql: true
    open-in-view: false
#  sql:
#    init:
#      mode: never
  batch:
    job:
      enabled: false
#    jdbc:
#      initialize-schema: never